source 'https://rubygems.org'
gem 'bundler'
gem 'sinatra', '2.0.1'
gem 'sinatra-contrib'
gem 'sequel'
gem 'mysql2' #For MySQL
gem 'pry'
gem 'pry-byebug'
gem 'racksh'
gem 'slim'
gem 'shotgun'
gem 'digest'